// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/create-profile': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/create-profile.post').default>>>>
    }
    '/api/email/analytics': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/email/analytics').default>>>>
    }
    '/api/email/queue': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/email/queue').default>>>>
    }
    '/api/email/send': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/email/send').default>>>>
    }
    '/api/email/templates': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/email/templates').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}